
name: Build and package RoBERTa-sequencing to Dockerhub
on: 
  push:
    branches: [master]
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: set auto-install of extensions
      run: az config set extension.use_dynamic_install=yes_without_prompt
      
    - name: install azure cli ml extension
      run: az extension add -n azure-cli-ml

    - name: attach workspace
      run: az ml folder attach -w "azure-learning-ws" -g "azure-learning-rg"

    - name: retrieve the model
      run: az ml model download -t "." --model-id "roberta-sequence:1"
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push flask-app container
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: sumitbanerjee/robertasentimentanalysis:latest

